### ISSUE TITLE
about README.md

### ISSUE THREAD

**Issue by grg121** [JJ/nodeo#20]
I'm trying to follow the steps suggested by this file but I find these problems: 

1) when I executed "cd node_modules/nodeo" it returned "no such  file or directory." It was because node_modules/nodeo was created outside of nodeo directory, in my home directory :S 
 
node app/ea.js and node app/classic-ea.js work (although I don't know what are they doing) 
Moreover, when I have tried to execute " npm install -g grunt-cli" it have returns: "Error: EACCES, mdir..." which I have solve executing "sudo npm install -g grunt-cli" (at start i had no idea of what was happening that made a lot of bugs .__. Then I realized I wasn't executing as admin. ) 

2) I receive more errors messages when try to execute grunt docco. 
First, I have installed docco with: "  npm install docco" and have no problem. But when I execute grunt docco, it doesn't work. "Fatal error: unable to find local grunt... I think that's because I hadn't execute "npm install grunt" I had only installed grunt's client... OK... now i execute grunt docco and receive more bugs... I think I have to do: "sudo npm install -g jshint" (I tried first without -g and it warned me about his use.) 

sudo npm install browserify...

at last I can't do nothing to run docco...

it retuns: Npm module "grunt-contrib-jshint" not found. It it installed?
and the same for docco and browserify... which I had just installed.
Am I installing them in a wrong directory or it doesn't matter? 

Well, I think it would be nice if we modify the README.md a bit in order to make it more easy to understand by inexperienced users like me :/

If I can if we can be of assistance, i'm willing to help. (And it would be nice to get the T-shit of HackToberFest, you know XD) 

~Saludos musicales.

**Comment by JJ** [comment]
2015-10-25 13:59 GMT+01:00 Francisco Navarro <notifications@github.com>:

> I'm trying to follow the steps suggested by this file but I find these
> problems:
>
> 1) when I executed "cd node_modules/nodeo" it returned "no such file or
> directory." It was because node_modules/nodeo was created outside of nodeo
> directory, in my home directory :S
>
> node app/ea.js and node app/classic-ea.js work (although I don't know what
> are they doing)
>

Fixing that on the README. `app` is not included in the distribution.

> Moreover, when I have tried to execute " npm install -g grunt-cli" it have
> returns: "Error: EACCES, mdir..." which I have solve executing "sudo npm
> install -g grunt-cli" (at start i had no idea of what was happening that
> made a lot of bugs .__. Then I realized I wasn't executing as admin. )
>

That's a node install issue. If you install node using sudo, you'll have to
do the same for all `-g` commands, which are global install.



> 2) I receive more errors messages when try to execute grunt docco.
> First, I have installed docco with: " npm install docco" and have no
> problem. But when I execute grunt docco, it doesn't work. "Fatal error:
> unable to find local grunt... I think that's because I hadn't execute "npm
> install grunt" I had only installed grunt's client... OK... now i execute
> grunt docco and receive more bugs... I think I have to do: "sudo npm
> install -g jshint" (I tried first without -g and it warned me about his
> use.)
>

A few more instructions should be needed, I guess.. I'll check everything
out.

> sudo npm install browserify...
>

You shouldn't need to install that.


> Well, I think it would be nice if we modify the README.md a bit in order
> to make it more easy to understand by inexperienced users like me :/


Will do.

You'll have to do a Pull Request to get the t-shirt, you know... not only
issues.

JJ
