### ISSUE TITLE
Vector Crossover Bug

### ISSUE THREAD

**Issue by mariosky** [JJ/nodeo#23]
I think there is an error in line 50,  splice from xoverpoint to xoverpoint.

**Comment by JJ** [comment]
I'll check, thanks for the report...

2016-03-25 3:54 GMT+01:00 Mario Garcia Valdez <notifications@github.com>:

> I think there is an error in line 50, splice from xoverpoint to xoverpoint.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/nodeo/issues/23>
>



-- 
JJ
